# Generated by Django 4.1.7 on 2023-08-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, default='clean', max_length=100, null=True),
        ),
    ]
