# Generated by Django 4.1.7 on 2023-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restotakeouts',
            name='status',
            field=models.CharField(default='on process', max_length=255),
            preserve_default=False,
        ),
    ]
