# Generated by Django 4.1.7 on 2023-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='transid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
