# Generated by Django 4.1.7 on 2023-06-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcounter',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
