# Generated by Django 4.1.7 on 2023-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
