# Generated by Django 4.1.7 on 2023-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='states',
            field=models.TextField(blank=True, null=True),
        ),
    ]
