# Generated by Django 4.1.7 on 2023-09-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='bedtypes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='nearat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
