# Generated by Django 4.1.7 on 2023-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('clientemail', models.EmailField(max_length=254)),
                ('clientaddress', models.CharField(max_length=255)),
                ('clientnationality', models.CharField(max_length=50)),
                ('clientType', models.CharField(max_length=50)),
                ('checkinDate', models.CharField(max_length=50)),
                ('checkoutDate', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('room_price', models.CharField(max_length=20)),
                ('numGuests', models.IntegerField()),
                ('contactNumber', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('itemID', models.CharField(max_length=128)),
                ('actualCheckoutDate', models.CharField(blank=True, max_length=50)),
                ('cancellationDate', models.CharField(blank=True, max_length=50)),
                ('isPaid', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('partialPayment', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('lastAccessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeisureItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('priceRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter', models.CharField(max_length=32)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=255)),
                ('clientemail', models.EmailField(max_length=254)),
                ('clientcontact', models.CharField(max_length=20)),
                ('clientaddress', models.CharField(max_length=255)),
                ('clientnationality', models.CharField(max_length=50)),
                ('clientType', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('totalAmountToPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('cashAmountPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payStatus', models.CharField(max_length=50)),
                ('discountMode', models.CharField(blank=True, max_length=50)),
                ('discountValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bookingID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookingID', models.CharField(max_length=255)),
                ('itemName', models.CharField(max_length=255)),
                ('itemType', models.CharField(max_length=50)),
                ('itemPriceRate', models.CharField(max_length=255)),
                ('purchaseQty', models.IntegerField()),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
