# Generated by Django 5.0.1 on 2024-01-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gokart',
            name='duebal',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gokart',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
