# Generated by Django 4.1.7 on 2023-07-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restotransaction',
            name='discountType',
            field=models.TextField(blank=True, null=True),
        ),
    ]
