# Generated by Django 4.1.7 on 2023-09-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_roomcategory_bedtypes_roomcategory_nearat'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='desc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
