# Generated by Django 4.1.7 on 2023-10-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_itemcategory_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
