# Generated by Django 4.1.7 on 2023-06-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_guestcounter_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcounter',
            name='history',
        ),
    ]
