# Generated by Django 4.1.7 on 2023-07-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(default='Clean', max_length=100),
        ),
    ]
