# Generated by Django 4.1.7 on 2023-09-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_transactionrecord_agentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
