# Generated by Django 4.1.7 on 2023-08-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_booking_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateField(auto_now_add=True, default='2023-08-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
