# Generated by Django 4.1.7 on 2023-08-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_room_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='clientType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='clientnationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
