# Generated by Django 4.1.7 on 2023-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_restotransaction_discounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoitem',
            name='imageFileName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
