# Generated by Django 4.1.7 on 2023-08-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_task_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
