# Generated by Django 4.1.7 on 2023-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nonCashReference',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
