# Generated by Django 4.1.7 on 2023-08-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_task_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completionDate',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
