# Generated by Django 4.1.7 on 2023-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
