# Generated by Django 4.1.7 on 2023-08-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_booking_clienttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
