# Generated by Django 4.1.7 on 2023-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
