# Generated by Django 4.1.7 on 2023-08-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_task_completiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actualStartTime',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
