# Generated by Django 4.1.7 on 2023-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_transaction_noncashreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='nonCashReference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
