# Generated by Django 4.1.7 on 2023-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_booking_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='clientemail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
