# Generated by Django 4.1.7 on 2023-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_booking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
