# Generated by Django 4.1.7 on 2023-09-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_package_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='leisureitem',
            name='status',
            field=models.CharField(blank=True, default='no package', max_length=100, null=True),
        ),
    ]
