# Generated by Django 4.1.7 on 2023-08-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_booking_clientemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cashOR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cashOS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
