# Generated by Django 4.1.7 on 2023-08-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_task_actualstarttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='person_dept',
            new_name='dept',
        ),
        migrations.AddField(
            model_name='task',
            name='person_role',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
