# Generated by Django 4.1.7 on 2023-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_person_dept_task_dept_task_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completionDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
