# Generated by Django 4.1.7 on 2023-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='processedBy',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='processedBy',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
