# Generated by Django 4.1.7 on 2023-09-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_leisureitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leisureitem',
            old_name='status',
            new_name='package_name',
        ),
    ]
