# Generated by Django 4.1.7 on 2023-08-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_transaction_cashor_transaction_cashos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cashOR',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cashOS',
        ),
    ]
