# Generated by Django 4.1.7 on 2023-04-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='dateCreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
