# Generated by Django 4.1.7 on 2023-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_booking_processedby_transaction_processedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='itemOption',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
