# Generated by Django 4.1.7 on 2023-08-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_transaction_agent_approvaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='numdays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='totalguest',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='totalpax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
