# Generated by Django 4.1.7 on 2023-09-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_transaction_agent_approvaldate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionrecord',
            old_name='transactionrecord_id',
            new_name='id',
        ),
    ]
