# Generated by Django 4.1.7 on 2023-04-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
