# Generated by Django 4.1.7 on 2023-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_transactionitem_numdays_transactionitem_totalguest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='currentroom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
