# Generated by Django 4.1.7 on 2023-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_stockitem_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
