# Generated by Django 4.1.7 on 2023-04-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('clientemail', models.EmailField(max_length=254)),
                ('clientaddress', models.CharField(max_length=255)),
                ('clientnationality', models.CharField(max_length=50)),
                ('clientType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customerid',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
