# Generated by Django 4.1.7 on 2023-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasesItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id', models.IntegerField()),
                ('purchase_id', models.IntegerField()),
                ('stock_id', models.IntegerField()),
                ('stock_sku', models.CharField(max_length=50, unique=True)),
                ('stock_name', models.CharField(max_length=255)),
                ('priceRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaseQty', models.IntegerField()),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
