# Generated by Django 4.1.7 on 2023-04-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_purchases_purchasesitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
