# Generated by Django 4.1.7 on 2023-04-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_stockitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='isAvailable',
        ),
    ]
