# Generated by Django 4.1.7 on 2023-04-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_remove_purchases_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesitem',
            name='stock_sku',
            field=models.CharField(max_length=50),
        ),
    ]
