# Generated by Django 4.1.7 on 2023-04-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_purchasesitem_stock_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
