# Generated by Django 4.1.7 on 2023-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_purchases_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('custumer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_id', models.IntegerField(blank=True, null=True)),
                ('sales_id', models.IntegerField(blank=True, null=True)),
                ('stock_id', models.IntegerField()),
                ('stock_sku', models.CharField(max_length=50)),
                ('stock_name', models.CharField(max_length=255)),
                ('priceRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchaseQty', models.IntegerField()),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_type', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PurchasesItem',
        ),
    ]
