# Generated by Django 4.1.7 on 2023-04-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='sucustomer_name',
            new_name='customer_name',
        ),
    ]
