# Generated by Django 4.1.7 on 2023-04-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_rename_sucustomer_name_sales_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitemrecord',
            old_name='custumer_name',
            new_name='customer_name',
        ),
    ]
