# Generated by Django 4.1.7 on 2023-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_rename_custumer_name_inventoryitemrecord_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='clientemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
