# Generated by Django 4.1.7 on 2023-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_alter_booking_clientemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemrecord',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
