# Generated by Django 4.1.7 on 2023-04-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_inventoryitemrecord_isadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitemrecord',
            name='isAdmin',
        ),
    ]
