# Generated by Django 4.1.7 on 2023-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_remove_inventoryitemrecord_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='clientemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
