# Generated by Django 4.1.7 on 2023-04-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='route',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
