# Generated by Django 4.1.7 on 2023-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_remove_booking_numguests_booking_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='groupkey',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='groupkey',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
