# Generated by Django 4.1.7 on 2023-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_booking_groupkey_transaction_groupkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='groupkey',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
