# Generated by Django 4.1.7 on 2023-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_transaction_cashremarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='itemRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
