# Generated by Django 4.1.7 on 2023-04-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_transactionitem_itemrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='itemRate',
        ),
    ]
