# Generated by Django 4.1.7 on 2023-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_remove_transactionitem_itemrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='numguests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
