# Generated by Django 4.1.7 on 2023-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_transactionrecord_numguests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='numguests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
