# Generated by Django 4.1.7 on 2023-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_remove_transactionrecord_numguests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='numguests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='numguests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
