# Generated by Django 4.1.7 on 2023-05-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_booking_numguests_transaction_numguests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='numguests',
        ),
    ]
