# Generated by Django 4.1.7 on 2023-05-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_remove_transaction_numguests'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
