# Generated by Django 4.1.7 on 2023-05-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_tasksrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='numguests',
        ),
    ]
