# Generated by Django 4.1.7 on 2023-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_remove_booking_numguests'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageUrl', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('stocks', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
