# Generated by Django 4.1.7 on 2023-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_restotransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='restotransaction',
            name='processedBy',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
