# Generated by Django 4.1.7 on 2023-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0044_restotransaction_processedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoTables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
