# Generated by Django 4.1.7 on 2023-05-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0046_restoorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoorders',
            name='processedBy',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restoorders',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
