from django.db import models

# Create your models here.
class CustomUser(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=128,null=True)
    FirstName = models.CharField(max_length=50)
    LastName = models.CharField(max_length=50)
    role = models.CharField(max_length=50)
    lastAccessed = models.DateTimeField(auto_now=True)
    isActive= models.BooleanField(default=True)

class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    clientemail = models.EmailField()
    clientaddress = models.CharField(max_length=255)
    clientnationality = models.CharField(max_length=50)
    clientType = models.CharField(max_length=50)
    checkinDate = models.CharField(max_length=50)
    checkoutDate = models.CharField(max_length=50)
    room_name = models.CharField(max_length=255)
    room_type = models.CharField(max_length=255)
    room_price = models.CharField(max_length=20)
    numGuests = models.IntegerField()
    contactNumber = models.CharField(max_length=20)
    status = models.CharField(max_length=50)
    itemID = models.CharField(max_length=128)
    actualCheckoutDate = models.CharField(max_length=50,blank=True)
    cancellationDate = models.CharField(max_length=50,blank=True)
    isPaid = models.CharField(max_length=50,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    totalPrice = models.DecimalField(max_digits=8, decimal_places=2)
    partialPayment = models.DecimalField(max_digits=8, decimal_places=2)
    processedBy = models.CharField(max_length=128)

class Room(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)  
    isAvailable = models.BooleanField(default=True)  

class LeisureItem(models.Model):
    id = models.AutoField(primary_key=True)
    item = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    priceRate = models.DecimalField(max_digits=10, decimal_places=2)
    counter = models.CharField(max_length=32)
    isAvailable = models.BooleanField(default=True)     

class Transaction(models.Model):
    id = models.AutoField(primary_key=True)
    clientname = models.CharField(max_length=255)
    clientemail = models.EmailField()
    clientcontact = models.CharField(max_length=20)
    clientaddress = models.CharField(max_length=255)
    clientnationality = models.CharField(max_length=50)
    clientType = models.CharField(max_length=50)
    transaction_date = models.DateField(auto_now_add=True)
    totalAmountToPay = models.DecimalField(max_digits=10, decimal_places=2)
    paymentMethod = models.CharField(max_length=50)
    nonCashReference = models.CharField(max_length=128,null=True, blank=True)
    cashAmountPay = models.DecimalField(max_digits=10, decimal_places=2)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    payStatus = models.CharField(max_length=50)
    discountMode = models.CharField(max_length=50, blank=True)
    discountValue = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    bookingID = models.CharField(max_length=255)
    processedBy = models.CharField(max_length=128)

class TransactionItem(models.Model):
    id = models.AutoField(primary_key=True)
    bookingID = models.CharField(max_length=255)
    itemName = models.CharField(max_length=255)
    itemType = models.CharField(max_length=50)
    itemPriceRate = models.CharField(max_length=255)
    purchaseQty = models.IntegerField()
    totalCost = models.DecimalField(max_digits=10, decimal_places=2)
    dateCreated = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=50)
    itemOption = models.CharField(max_length=50)