from django.urls import re_path
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    re_path(r'^task/$', task_list, name='task-list'),
    re_path(r'^task/(?P<pk>\d+)/$', task_list, name='task-detail'),
    re_path(r'^task/filter/$', task_filter, name='task-filter'),
    re_path(r'^task/delete/(?P<pk>\d+)/$', task_delete, name='task-delete'),
    re_path(r'^bugreports/savefile', SaveFile),
    re_path(r'^restoitem/savefile', SaveFile),
    re_path(r'^bugreports/$', bugreports_list, name='bugreports-list'),
    re_path(r'^bugreports/(?P<pk>\d+)/$',
            bugreports_list, name='bugreports-detail'),
    re_path(r'^transactions_itemizer/(?P<prevday>\d+)/$',
            get_transactions_with_items, name='transactions'),
    re_path(r'^login/$', login, name='login'),
    re_path(r'^guestcounter/$', guestcounter_list, name='guestcounter-list'),
    re_path(r'^guestcounter/(?P<pk>\d+)/$',
            guestcounter_list, name='guestcounter-detail'),
    re_path(r'^restoorders/$', restoorders_list, name='restoorders-list'),
    re_path(r'^restoorders/(?P<pk>\d+)/$',
            restoorders_list, name='restoorders-detail'),
    re_path(r'^restoorders/filter/$', restoorders_filter,
            name='restoorders-filter'),
    re_path(r'^restoonholds/$', restoonholds_list, name='restoonholds-list'),
    re_path(r'^restoonholds/(?P<pk>\d+)/$',
            restoonholds_list, name='restoonholds-detail'),
    re_path(r'^restotakeouts/$', restotakeouts_list,
            name='restotakeouts-list'),
    re_path(r'^restotakeouts/(?P<pk>\d+)/$',
            restotakeouts_list, name='restotakeouts-detail'),
    re_path(r'^restotakeouts/delete/(?P<pk>\d+)/$',
            restotakeouts_delete, name='restotakeouts-delete'),
    re_path(r'^restotables/$', restotables_list, name='restotables-list'),
    re_path(r'^restotables/(?P<pk>\d+)/$',
            restotables_list, name='restotables-detail'),
    re_path(r'^restotables/filter/$', restotables_filter,
            name='restotables-filter'),
    re_path(r'^restotransaction/filter/$', restotransaction_filter,
            name='restotransaction-filter'),
    re_path(r'^restotransaction/delete/(?P<pk>\d+)/$',
            restotransaction_delete, name='restotransaction-delete'),
    re_path(r'^restotransaction/$', restotransaction_list,
            name='restotransaction-list'),
    re_path(r'^restoitem/$', restoitem_list, name='restoitem-list'),
    re_path(r'^restoitem/(?P<pk>\d+)/$',
            restoitem_list, name='restoitem-detail'),
    re_path(r'^restoitem/filter/$', restoitem_filter, name='restoitem-filter'),
    re_path(r'^task/record/$', tasksrecord_list, name='taskrecord-list'),
    re_path(r'^transaction/record/$', transactionrecord_list,
            name='transactionRecord-list'),
    re_path(r'^transaction/record/(?P<pk>\d+)/$',
            transactionrecord_list, name='transactionRecord-detail'),
    re_path(r'^transaction/record/delete/(?P<pk>\d+)/$',
            transactionrecord_delete, name='transactionrecord-delete'),
    re_path(r'^transaction/record/filter/$', transactionrecord_filter,
            name='transaction-record-filter'),
    re_path(r'^sales/$', sales_list, name='sales-list'),
    re_path(r'^sales/(?P<pk>\d+)/$', sales_list, name='sales-detail'),
    re_path(r'^sales/filter/$', sales_filter, name='sales-filter'),
    re_path(r'^purchases/$', purchases_list, name='purchases-list'),
    re_path(r'^purchases/(?P<pk>\d+)/$',
            purchases_list, name='purchases-detail'),
    re_path(r'^purchases/filter/$', purchases_filter, name='purchases-filter'),
    re_path(r'^inventory/item/$', inventoryitemrecord_list,
            name='inventoryitemrecord-list'),
    re_path(r'^inventory/item/(?P<pk>\d+)/$', inventoryitemrecord_list,
            name='inventoryitemrecord-detail'),
    re_path(r'^inventory/item/filter/$', inventoryitemrecord_filter,
            name='inventoryitemrecord-filter'),
    re_path(r'^supplier/$', supplier_list, name='supplier-list'),
    re_path(r'^supplier/(?P<pk>\d+)/$', supplier_list, name='supplier-detail'),
    re_path(r'^supplier/filter/$', supplier_filter, name='supplier-filter'),
    re_path(r'^stockitem/$', stockitem_list, name='stockitem-list'),
    re_path(r'^stockitem/(?P<pk>\d+)/$',
            stockitem_list, name='stockitem-detail'),
    re_path(r'^stockitem/filter/$', stockitem_filter, name='stockitem-filter'),
    re_path(r'^users/$', users_list, name='users-list'),
    re_path(r'^users/(?P<pk>\d+)/$', users_list, name='users-detail'),
    re_path(r'^users/filter/$', users_filter, name='users-filter'),
    re_path(r'^user/delete/(?P<pk>\d+)/$', user_delete, name='user-delete'),
    re_path(r'^bookings/$', booking_list, name='booking-list'),
    re_path(r'^bookings/filter/$', booking_filter, name='booking-filter'),
    re_path(r'^bookings/(?P<pk>\d+)/$', booking_list, name='booking-detail'),
    re_path(r'^bookings/delete/(?P<pk>\d+)/$',
            booking_delete, name='booking-delete'),
    re_path(r'^rooms/category/filter/$',
            roomcategory_filter, name='roomcategory-filter'),
    re_path(r'^rooms/category/$', roomcategory_list, name='roomcategory-list'),
    re_path(r'^rooms/category/(?P<pk>\d+)/$',
            roomcategory_list, name='roomcategory-detail'),

    re_path(r'^agents/$', agents_list, name='agents-list'),
    re_path(r'^agents/(?P<pk>\d+)/$', agents_list, name='agents-detail'),
    re_path(r'^agents/filter/$', agents_filter, name='agents-filter'),
    re_path(r'^agents/delete/(?P<pk>\d+)/$',
            agents_delete, name='agents-delete'),

    re_path(r'^package/$', package_list, name='package-list'),
    re_path(r'^package/(?P<pk>\d+)/$', package_list, name='package-detail'),
    re_path(r'^package/filter/$', package_filter, name='package-filter'),
    re_path(r'^package/delete/(?P<pk>\d+)/$',
            package_delete, name='package-delete'),

    re_path(r'^rooms/$', room_list, name='room-list'),
    re_path(r'^rooms/(?P<pk>\d+)/$', room_list, name='room-detail'),
    re_path(r'^rooms/filter/$', rooms_filter, name='rooms-filter'),
    re_path(r'^rooms/delete/(?P<pk>\d+)/$', room_delete, name='room-delete'),
    re_path(r'^leisures/$', leisure_list, name='leisure-list'),
    re_path(r'^leisures/(?P<pk>\d+)/$', leisure_list, name='leisure-detail'),
    re_path(r'^leisures/filter/$', leisure_filter, name='leisure-filter'),
    re_path(r'^transaction/$', transaction_list, name='transaction-list'),
    re_path(r'^transaction/(?P<pk>\d+)/$',
            transaction_list, name='transaction-detail'),
    re_path(r'^transaction/delete/(?P<pk>\d+)/$',
            transaction_delete, name='transaction-delete'),
    re_path(r'^transaction/filter/$', transaction_filter,
            name='transaction-filter'),
    re_path(r'^transaction/item/$', transactionitem_list,
            name='transactionItem-list'),
    re_path(r'^transaction/item/(?P<pk>\d+)/$',
            transactionitem_list, name='transactionItem-detail'),
    re_path(r'^transaction/item/delete/(?P<pk>\d+)/$',
            transactionitem_delete, name='transactionItem-delete'),
    re_path(r'^transaction/item/filter/$',
            transactionitem_filter, name='transactionItem-list'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
